import Foundation

/// A point in shape-local space, normalised to roughly −1…1.
public struct Vertex: Sendable, Hashable, Codable {
    public var x: Double
    public var y: Double

    public init(x: Double, y: Double) {
        self.x = x
        self.y = y
    }
}

/// The geometry behind every visual puzzle, expressed as plain polygons.
///
/// This lives in `Core` rather than in the view for one concrete reason: an earlier
/// version built the same outlines inside SwiftUI, and a self-intersecting path silently
/// rendered as *nothing* — invisible options that a player could never select, and a
/// broken-looking matrix grid. Shapes generated by arithmetic (a crescent from two
/// intersecting circles, for example) can always degenerate, and the only reliable defence
/// is to generate them here and assert on them in a test.
///
/// The view layer turns these vertices into a `Path` and applies fill and rotation. It does
/// no geometry of its own.
public enum ShapeGeometry {
    /// Shapes whose silhouette actually changes when you rotate them by 90°.
    ///
    /// A cross or a square rotated 90° is indistinguishable from itself, so using one in a
    /// rotation or matrix item produces an item with no visible rule and no visible answer.
    /// Every generator whose difficulty depends on rotation draws from this list only.
    public static let rotationSensitive: [ShapeSpec.Shape] = [
        .triangle, .arrow, .crescent, .pentagon, .star, .hexagon, .diamond,
    ]

    /// Shapes that have a left and a right, so mirroring them is observable.
    public static let handed: [ShapeSpec.Shape] = [
        .arrow, .crescent, .triangle, .star, .pentagon, .hexagon, .diamond, .bar,
    ]

    /// Closed outline for a shape, in shape-local units. `radius` is the bounding half-size.
    public static func outline(for shape: ShapeSpec.Shape, radius: Double) -> [Vertex] {
        switch shape {
        case .circle, .ring:
            return self.polygon(sides: 64, radius: radius)

        case .square:
            return [
                Vertex(x: -radius, y: -radius), Vertex(x: radius, y: -radius),
                Vertex(x: radius, y: radius), Vertex(x: -radius, y: radius),
            ]

        case .diamond:
            return [
                Vertex(x: 0, y: -radius), Vertex(x: radius, y: 0),
                Vertex(x: 0, y: radius), Vertex(x: -radius, y: 0),
            ]

        case .triangle:
            return [
                Vertex(x: 0, y: -radius),
                Vertex(x: radius * 0.92, y: radius * 0.75),
                Vertex(x: -radius * 0.92, y: radius * 0.75),
            ]

        case .pentagon:
            return self.polygon(sides: 5, radius: radius)

        case .hexagon:
            return self.polygon(sides: 6, radius: radius)

        case .star:
            return self.starPolygon(points: 5, radius: radius, innerRatio: 0.44)

        case .cross:
            let arm = radius * 0.38
            return [
                Vertex(x: -arm, y: -radius), Vertex(x: arm, y: -radius),
                Vertex(x: arm, y: -arm), Vertex(x: radius, y: -arm),
                Vertex(x: radius, y: arm), Vertex(x: arm, y: arm),
                Vertex(x: arm, y: radius), Vertex(x: -arm, y: radius),
                Vertex(x: -arm, y: arm), Vertex(x: -radius, y: arm),
                Vertex(x: -radius, y: -arm), Vertex(x: -arm, y: -arm),
            ]

        case .bar:
            let height = radius * 0.60
            let width = radius * 0.34
            return [
                Vertex(x: -width, y: -height), Vertex(x: width, y: -height),
                Vertex(x: width, y: height), Vertex(x: -width, y: height),
            ]

        case .arrow:
            // Asymmetric on purpose: this is the shape that makes a mirror visibly
            // different from a rotation.
            return [
                Vertex(x: -radius, y: -radius * 0.30),
                Vertex(x: radius * 0.15, y: -radius * 0.30),
                Vertex(x: radius * 0.15, y: -radius * 0.82),
                Vertex(x: radius, y: 0),
                Vertex(x: radius * 0.15, y: radius * 0.82),
                Vertex(x: radius * 0.15, y: radius * 0.30),
                Vertex(x: -radius, y: radius * 0.30),
            ]

        case .crescent:
            return self.crescent(radius: radius)
        }
    }

    /// Silhouette rotated by a multiple of 90°. Used by tests to prove that a shape's
    /// appearance genuinely changes under rotation.
    public static func outline(
        for shape: ShapeSpec.Shape, radius: Double, quarterTurns: Int
    ) -> [Vertex] {
        let turns = ((quarterTurns % 4) + 4) % 4
        return self.outline(for: shape, radius: radius).map { vertex in
            switch turns {
            case 0: return vertex
            case 1: return Vertex(x: -vertex.y, y: vertex.x)
            case 2: return Vertex(x: -vertex.x, y: -vertex.y)
            default: return Vertex(x: vertex.y, y: -vertex.x)
            }
        }
    }

    // MARK: - Builders

    private static func polygon(sides: Int, radius: Double) -> [Vertex] {
        (0..<sides).map { index in
            let angle = 2 * Double.pi * Double(index) / Double(sides) - Double.pi / 2
            return Vertex(x: radius * cos(angle), y: radius * sin(angle))
        }
    }

    private static func starPolygon(points: Int, radius: Double, innerRatio: Double) -> [Vertex] {
        (0..<(points * 2)).map { index in
            let angle = Double.pi * Double(index) / Double(points) - Double.pi / 2
            let length = index.isMultiple(of: 2) ? radius : radius * innerRatio
            return Vertex(x: length * cos(angle), y: length * sin(angle))
        }
    }

    /// The region of one circle that lies outside a second, offset circle.
    ///
    /// Built from the two intersection points of the circles so the result is a genuine
    /// crescent. The offset is chosen to guarantee the circles actually intersect
    /// (`|r1 − r2| < d < r1 + r2`), which is what stops the polygon collapsing to a line.
    private static func crescent(radius: Double) -> [Vertex] {
        let outerRadius = radius
        let innerRadius = radius * 0.78
        let offset = radius * 0.42

        let a = (offset * offset - innerRadius * innerRadius + outerRadius * outerRadius) / (2 * offset)
        let hSquared = outerRadius * outerRadius - a * a
        guard hSquared > 0.0001 * outerRadius * outerRadius else {
            // Circles do not intersect. Fall back to a plain disc rather than emit a
            // degenerate polygon, which would draw as nothing.
            return self.polygon(sides: 48, radius: radius)
        }
        let h = hSquared.squareRoot()

        let outerStart = atan2(h, a)
        // Trace the outer circle the long way round, away from the bite.
        let outerArc = self.arc(
            center: Vertex(x: 0, y: 0), radius: outerRadius,
            from: outerStart, sweeping: .counterClockwise, total: 2 * Double.pi - 2 * outerStart
        )
        let innerStart = atan2(-h, a - offset)
        let innerArc = self.arc(
            center: Vertex(x: offset, y: 0), radius: innerRadius,
            from: innerStart, sweeping: .clockwise, total: 2 * Double.pi - 2 * abs(innerStart)
        )
        return outerArc + innerArc
    }

    private enum Sweep { case clockwise, counterClockwise }

    private static func arc(
        center: Vertex, radius: Double, from start: Double, sweeping direction: Sweep, total: Double
    ) -> [Vertex] {
        let steps = 40
        let sign = direction == .counterClockwise ? 1.0 : -1.0
        return (0...steps).map { step in
            let angle = start + sign * total * Double(step) / Double(steps)
            return Vertex(x: center.x + radius * cos(angle), y: center.y + radius * sin(angle))
        }
    }

    // MARK: - Measurement

    /// Shoelace area. Used by tests to guarantee a shape is actually drawable.
    public static func area(of vertices: [Vertex]) -> Double {
        guard vertices.count > 2 else { return 0 }
        var total = 0.0
        for index in vertices.indices {
            let current = vertices[index]
            let next = vertices[(index + 1) % vertices.count]
            total += current.x * next.y - next.x * current.y
        }
        return abs(total) / 2
    }

    public static func boundingBox(of vertices: [Vertex]) -> (minX: Double, minY: Double, maxX: Double, maxY: Double)? {
        guard let first = vertices.first else { return nil }
        var box = (minX: first.x, minY: first.y, maxX: first.x, maxY: first.y)
        for vertex in vertices.dropFirst() {
            box.minX = Swift.min(box.minX, vertex.x)
            box.minY = Swift.min(box.minY, vertex.y)
            box.maxX = Swift.max(box.maxX, vertex.x)
            box.maxY = Swift.max(box.maxY, vertex.y)
        }
        return box
    }
}